import {
    HomeOutlined,
    AppstoreOutlined,
    UnorderedListOutlined,
    ToolOutlined,
    UserOutlined,
    IdcardOutlined,
    BarChartOutlined,
    LineChartOutlined,
    PieChartOutlined,
    AreaChartOutlined
  } from '@ant-design/icons';  
export default [
    {
        title:'首页',
        key:'home',
        icon:<HomeOutlined/>,
        path:'/admin/home'
    },
    {
        title:'商品',
        key:'prod',
        icon:<AppstoreOutlined/>,
        children:[
            {
                title:'分类管理',
                key:'category',
                icon:<UnorderedListOutlined/>,
                path:'/admin/prod/category'
            },
            {
                title:'商品管理',
                key:'product',
                icon:<ToolOutlined/>,
                path:'/admin/prod/product'
            }
        ]
    },
    {
        title:'用户管理',
        key:'user',
        icon:<UserOutlined/>,
        path:'/admin/user'
    },
    {
        title:'角色管理',
        key:'role',
        icon:<IdcardOutlined/>,
        path:'/admin/role'
    },
    {
        title:'图形图表',
        key:'charts',
        icon:<AreaChartOutlined />,
        children:[
            {
                title:'柱形图',
                key:'bar',
                icon:<BarChartOutlined/>,
                path:'/admin/charts/bar'
            },
            {
                title:'折线图',
                key:'line',
                icon:<LineChartOutlined/>,
                path:'/admin/charts/line'
            },
            {
                title:'饼图',
                key:'pie',
                icon:<PieChartOutlined/>,
                path:'/admin/charts/pie'
            }
        ]
    }
]